# Server Configuration
server.port=8080
# Enable Swagger UI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Optional: Custom title
springdoc.swagger-ui.title=Statista-Proxy-API Documentation

# Enable debug
debug=true